In [ ]:
"""SISTEMA DE RECOMENDAÇÃO DE FILMES BY KATOMBELA 
 
Neste codigo foi usado datasets baixados do Kaggle. 

https://www.kaggle.com/datasets/rounakbanik/the-movies-dataset?resource=download  ver DataSet Link """

In [5]:
import pandas as pd
import numpy as np

In [42]:
filmes = pd.read_csv('movies_metadata.csv', low_memory=False)
filmes.head(5)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [43]:
avaliacoes = pd.read_csv('ratings.csv')
avaliacoes.head()

   userId  movieId  rating   timestamp
0       1      110     1.0  1425941529
1       1      147     4.5  1425942435
2       1      858     5.0  1425941523
3       1     1221     5.0  1425941546
4       1     1246     5.0  1425941556

In [58]:
 
filmes = filmes [['id','original_title','original_language','vote_count']]
 
filmes.rename(columns = {'id':'ID_FILME','original_title':'TITULO','original_language':'LINGUAGEM','vote_count':'QT_AVALIACOES'}, inplace = True)

filmes.head()

    ID_FILME                                   TITULO LINGUAGEM  QT_AVALIACOES
9        710                                GoldenEye        en         1194.0
68     10634                                   Friday        en          513.0
69       755                      From Dusk Till Dawn        en         1644.0
153     5894                         Blue in the Face        en           28.0
178     9070  Mighty Morphin Power Rangers: The Movie        en          153.0

In [59]:
avaliacoes = avaliacoes[['userId','movieId','rating']]
avaliacoes.rename(columns = {'userId':'ID_USUARIO', 'MOVIEiD':'FILME_ID', 'rating':'AVALIACAO'}, inplace = True)
avaliacoes.head()

KeyError: "None of [Index(['userId', 'movieId', 'rating'], dtype='object')] are in the [columns]"

In [45]:

avaliacoes.rename(columns = {'movieId':'FILME_ID'}, inplace = True)
avaliacoes.head()

   ID_USUARIO  FILME_ID  AVALIACAO
0           1       110        1.0
1           1       147        4.5
2           1       858        5.0
3           1      1221        5.0
4           1      1246        5.0

In [60]:

avaliacoes.rename(columns = {'FILME_ID':'ID_FILME'}, inplace = True)
avaliacoes.head()

      ID_USUARIO  ID_FILME  AVALIACAO
1710          24         1        4.0
1711          24         2        3.0
1712          24         6        4.0
1713          24        16        3.0
1714          24        17        3.0

In [61]:
filmes.isna()

       ID_FILME  TITULO  LINGUAGEM  QT_AVALIACOES
9         False   False      False          False
68        False   False      False          False
69        False   False      False          False
153       False   False      False          False
178       False   False      False          False
...         ...     ...        ...            ...
44274     False   False      False          False
44674     False   False      False          False
44821     False   False      False          False
44842     False   False      False          False
45029     False   False      False          False

[693 rows x 4 columns]

In [62]:
filmes.isna().sum()

ID_FILME         0
TITULO           0
LINGUAGEM        0
QT_AVALIACOES    0
dtype: int64

In [63]:
filmes.dropna(inplace = True)

In [64]:
filmes.isna().sum()

ID_FILME         0
TITULO           0
LINGUAGEM        0
QT_AVALIACOES    0
dtype: int64

In [65]:
avaliacoes['ID_USUARIO'].value_counts()

ID_USUARIO
45811     18276
8659       9279
270123     7638
179792     7515
228291     7410
          ...
255583      501
252594      501
197937      501
181206      501
77371       501
Name: count, Length: 9452, dtype: int64

In [66]:
qt_avaliacoes = avaliacoes['ID_USUARIO'].value_counts() > 500

In [69]:
y = qt_avaliacoes[qt_avaliacoes].index
y.shape

(9452,)

In [70]:
avaliacoes.shape

(8543119, 3)

In [71]:
avaliacoes = avaliacoes[avaliacoes['ID_USUARIO'].isin(y)]
avaliacoes.shape

(8543119, 3)

In [73]:
avaliacoes.head()

      ID_USUARIO  ID_FILME  AVALIACAO
1710          24         1        4.0
1711          24         2        3.0
1712          24         6        4.0
1713          24        16        3.0
1714          24        17        3.0

In [74]:
filmes.head()

    ID_FILME                                   TITULO LINGUAGEM  QT_AVALIACOES
9        710                                GoldenEye        en         1194.0
68     10634                                   Friday        en          513.0
69       755                      From Dusk Till Dawn        en         1644.0
153     5894                         Blue in the Face        en           28.0
178     9070  Mighty Morphin Power Rangers: The Movie        en          153.0

In [75]:
filmes = filmes[filmes['QT_AVALIACOES'] > 500]

In [76]:
filmes.head()

    ID_FILME               TITULO LINGUAGEM  QT_AVALIACOES
9        710            GoldenEye        en         1194.0
68     10634               Friday        en          513.0
69       755  From Dusk Till Dawn        en         1644.0
219     2292               Clerks        en          769.0
256       11            Star Wars        en         6778.0

In [79]:
filmes_lang = filmes['LINGUAGEM'].value_counts()
filmes_lang.head(10)

LINGUAGEM
en    386
cn      2
sv      2
id      2
it      1
fr      1
pt      1
es      1
da      1
Name: count, dtype: int64

In [80]:
filmes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 397 entries, 9 to 44842
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID_FILME       397 non-null    object
 1   TITULO         397 non-null    object
 2   LINGUAGEM      397 non-null    object
 3   QT_AVALIACOES  397 non-null    float64
dtypes: float64(1), object(3)
memory usage: 15.5+ KB

In [81]:
avaliacoes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8543119 entries, 1710 to 26023521
Data columns (total 3 columns):
 #   Column      Dtype
---  ------      -----
 0   ID_USUARIO  int64
 1   ID_FILME    int64
 2   AVALIACAO   float64
dtypes: float64(1), int64(2)
memory usage: 260.7 MB

In [82]:
filmes['ID_FILME'] = filmes['ID_FILME'].astype(int)

In [83]:
filmes.shape

(397, 4)

In [84]:
filmes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 397 entries, 9 to 44842
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID_FILME       397 non-null    int32
 1   TITULO         397 non-null    object
 2   LINGUAGEM      397 non-null    object
 3   QT_AVALIACOES  397 non-null    float64
dtypes: float64(1), int32(1), object(2)
memory usage: 14.0+ KB

In [85]:
filmes_e_avaliacoes = avaliacoes.merge(filmes, on = 'ID_FILME')
filmes_e_avaliacoes.head()

,ID_USUARIO,ID_FILME,AVALIACAO,TITULO,LINGUAGEM,QT_AVALIACOES
0,24,58,5.0,Pirates of the Caribbean: Dead Man's Chest,en,5380.0
1,24,440,2.0,Aliens vs Predator: Requiem,en,758.0
2,24,588,4.0,Silent Hill,en,1093.0
3,24,608,5.0,Men in Black II,en,3188.0
4,24,714,5.0,Tomorrow Never Dies,en,941.0

In [86]:
filmes_e_avaliacoes.isna().sum()

ID_USUARIO       0
ID_FILME         0
AVALIACAO        0
TITULO           0
LINGUAGEM        0
QT_AVALIACOES    0
dtype: int64

In [87]:
filmes_e_avaliacoes.head(20)

,ID_USUARIO,ID_FILME,AVALIACAO,TITULO,LINGUAGEM,QT_AVALIACOES
0,24,58,5.0,Pirates of the Caribbean: Dead Man's Chest,en,5380.0
1,24,440,2.0,Aliens vs Predator: Requiem,en,758.0
2,24,588,4.0,Silent Hill,en,1093.0
3,24,608,5.0,Men in Black II,en,3188.0
4,24,714,5.0,Tomorrow Never Dies,en,941.0
5,24,1091,4.0,The Thing,en,1629.0
6,24,1246,4.0,Rocky Balboa,en,858.0
7,24,1271,3.0,300,en,5092.0
8,24,1735,4.0,The Mummy: Tomb of the Dragon Emperor,en,1418.0
9,24,1894,2.0,Star Wars: Episode II - Attack of the Clones,en,4074.0
10,24,1895,2.0,Star Wars: Episode III - Revenge of the Sith,en,4200.0
11,46,24,3.0,Kill Bill: Vol. 1,en,5091.0
12,46,88,4.5,Dirty Dancing,en,1371.0
13,46,105,1.5,Back to the Future,en,6239.0
14,46,122,3.0,The Lord of the Rings: The Return of the King,en,8226.0
15,46,163,3.0,Ocean's Twelve,en,2169.0
16,46,165,4.0,Back to the Future Part II,en,3926.0
17,46,196,3.0,Back to the Future Part III,en,2978.0
18,46,253,4.5,Live and Let Die,en,540.0
19,46,329,2.5,Jurassic Park,en,4956.0

In [88]:
filmes_e_avaliacoes.drop_duplicates(['ID_USUARIO','ID_FILME'], inplace = True)

In [89]:
filmes_e_avaliacoes.shape

(168020, 6)

In [90]:
del filmes_e_avaliacoes['ID_FILME']
filmes_e_avaliacoes.head()

,ID_USUARIO,AVALIACAO,TITULO,LINGUAGEM,QT_AVALIACOES
0,24,5.0,Pirates of the Caribbean: Dead Man's Chest,en,5380.0
1,24,2.0,Aliens vs Predator: Requiem,en,758.0
2,24,4.0,Silent Hill,en,1093.0
3,24,5.0,Men in Black II,en,3188.0
4,24,5.0,Tomorrow Never Dies,en,941.0

In [91]:
filmes_p = filmes_e_avaliacoes.pivot_table(columns = 'ID_USUARIO', index = 'TITULO', values = 'AVALIACAO')

In [92]:
filmes_e_avaliacoes.head(20)

,ID_USUARIO,AVALIACAO,TITULO,LINGUAGEM,QT_AVALIACOES
0,24,5.0,Pirates of the Caribbean: Dead Man's Chest,en,5380.0
1,24,2.0,Aliens vs Predator: Requiem,en,758.0
2,24,4.0,Silent Hill,en,1093.0
3,24,5.0,Men in Black II,en,3188.0
4,24,5.0,Tomorrow Never Dies,en,941.0
5,24,4.0,The Thing,en,1629.0
6,24,4.0,Rocky Balboa,en,858.0
7,24,3.0,300,en,5092.0
8,24,4.0,The Mummy: Tomb of the Dragon Emperor,en,1418.0
9,24,2.0,Star Wars: Episode II - Attack of the Clones,en,4074.0
10,24,2.0,Star Wars: Episode III - Revenge of the Sith,en,4200.0
11,46,3.0,Kill Bill: Vol. 1,en,5091.0
12,46,4.5,Dirty Dancing,en,1371.0
13,46,1.5,Back to the Future,en,6239.0
14,46,3.0,The Lord of the Rings: The Return of the King,en,8226.0
15,46,3.0,Ocean's Twelve,en,2169.0
16,46,4.0,Back to the Future Part II,en,3926.0
17,46,3.0,Back to the Future Part III,en,2978.0
18,46,4.5,Live and Let Die,en,540.0
19,46,2.5,Jurassic Park,en,4956.0

In [93]:
filmes_p.head(20)

ID_USUARIO,24,46,120,132,150,229,231,251,332,340,...,270555,270564,270579,270631,270634,270654,270684,270734,270769,270887
TITULO,,,,,,,,,,,,,,,,,,,,,
30 Days of Night,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
300,3.0,NaN,3.5,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,3.0,3.0,NaN,NaN,NaN,1.5,NaN,4.0,4.0,NaN
A View to a Kill,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,4.0
AVP: Alien vs. Predator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Aladdin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Alien,NaN,NaN,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.5,NaN,NaN,NaN,NaN,2.0,NaN,4.0,NaN,NaN
Aliens vs Predator: Requiem,2.0,4.0,3.5,3.0,NaN,NaN,2.5,NaN,NaN,3.5,...,4.0,3.0,3.5,NaN,NaN,3.5,4.0,4.0,4.0,4.0
Alvin and the Chipmunks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
American Pie Presents: The Naked Mile,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ant-Man,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Austin Powers in Goldmember,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.5,NaN,NaN,NaN,NaN,2.0,NaN,NaN
Avengers: Age of Ultron,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Back to the Future,NaN,1.5,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,3.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,5.0
Back to the Future Part II,NaN,4.0,NaN,NaN,NaN,NaN,3.5,3.0,3.5,NaN,...,2.5,2.5,3.5,NaN,NaN,NaN,3.0,2.0,NaN,5.0
Back to the Future Part III,NaN,3.0,NaN,NaN,2.0,3.0,2.5,3.0,NaN,NaN,...,NaN,3.0,NaN,NaN,NaN,NaN,3.0,NaN,2.0,5.0
Bambi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Basic Instinct,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Batman Begins,NaN,NaN,4.0,4.0,NaN,4.0,NaN,NaN,NaN,NaN,...,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Before Sunset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Blade Runner,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [94]:
filmes_p.fillna(0, inplace = True)
filmes_p.head(20)

ID_USUARIO,24,46,120,132,150,229,231,251,332,340,...,270555,270564,270579,270631,270634,270654,270684,270734,270769,270887
TITULO,,,,,,,,,,,,,,,,,,,,,
30 Days of Night,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
300,3.0,0.0,3.5,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,3.0,3.0,0.0,0.0,0.0,1.5,0.0,4.0,4.0,0.0
A View to a Kill,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,4.0
AVP: Alien vs. Predator,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Aladdin,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Alien,0.0,0.0,4.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.5,0.0,0.0,0.0,0.0,2.0,0.0,4.0,0.0,0.0
Aliens vs Predator: Requiem,2.0,4.0,3.5,3.0,0.0,0.0,2.5,0.0,0.0,3.5,...,4.0,3.0,3.5,0.0,0.0,3.5,4.0,4.0,4.0,4.0
Alvin and the Chipmunks,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
American Pie Presents: The Naked Mile,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Ant-Man,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Austin Powers in Goldmember,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.5,0.0,0.0,0.0,0.0,2.0,0.0,0.0
Avengers: Age of Ultron,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Back to the Future,0.0,1.5,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,3.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,5.0
Back to the Future Part II,0.0,4.0,0.0,0.0,0.0,0.0,3.5,3.0,3.5,0.0,...,2.5,2.5,3.5,0.0,0.0,0.0,3.0,2.0,0.0,5.0
Back to the Future Part III,0.0,3.0,0.0,0.0,2.0,3.0,2.5,3.0,0.0,0.0,...,0.0,3.0,0.0,0.0,0.0,0.0,3.0,0.0,2.0,5.0
Bambi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Basic Instinct,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Batman Begins,0.0,0.0,4.0,4.0,0.0,4.0,0.0,0.0,0.0,0.0,...,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Before Sunset,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Blade Runner,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [95]:
from scipy.sparse import csr_matrix

In [96]:
films_parsed = csr_matrix(filmes_p)

In [97]:
type(films_parsed)

scipy.sparse._csr.csr_matrix

In [103]:
from sklearn.neighbors import NearestNeighbors
modelo = NearestNeighbors(algorithm = 'brute')
modelo.fit(films_parsed)

NearestNeighbors(algorithm='brute')

In [106]:
 # testando com o filme Aliens vs Predator: Requiem
distances, sugestions = modelo.kneighbors(filmes_p.filter(items = ['Aliens vs Predator: Requiem'], axis=0).values.reshape(1, -1))

for i in range(len(sugestions)):
    print(filmes_p.index[sugestions[i]])

Index(['Aliens vs Predator: Requiem', 'Star Wars', 'Monsters, Inc.',
       'Star Wars: Episode II - Attack of the Clones', 'The Thing'],
      dtype='object', name='TITULO')

In [108]:
 # testando com o filme Avengers: Age of Ultron	
distances, sugestions = modelo.kneighbors(filmes_p.filter(items = ['Avengers: Age of Ultron'], axis=0).values.reshape(1, -1))

for i in range(len(sugestions)):
    print(filmes_p.index[sugestions[i]])

Index(['Avengers: Age of Ultron', 'Paranormal Activity 3', 'RED 2', 'Bambi',
       'Grown Ups 2'],
      dtype='object', name='TITULO')

In [ ]:
 # testando com o filme 30 Days of Night	
distances, sugestions = modelo.kneighbors(filmes_p.filter(items = ['30 Days of Night'], axis=0).values.reshape(1, -1))


for i in range(len(sugestions)):
    print(filmes_p.index[sugestions[i]])

: